<?php 

	/**
	 *@file
	 *splash_me.module
	 */

	//Create the menu item for the admin panel
	function splash_me_menu() {
  	
	  	$items = array();

		$items['admin/config/lazypixel/splash_me'] = array(
			'title' => 'Splash Me',
			'description' => 'Configuration for the Splash Me module.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('splash_me_admin'),
			'access arguments' => array('administer users'),
			'file' => '/includes/splash_me.admin.inc',
			'type' => MENU_NORMAL_ITEM,
		);

		//Setup callback function for the above menu
		$items['splash-me-node-results'] = array(
			'page callback' => 'splash_me_get_nodes',
			'access arguments' => array('view published content'),
			'type' => MENU_CALLBACK,
		);

		return $items;

	}
	
	function splash_me_init() {	


		//Get the values from admin page
		$splashPage = variable_get('splash_me_node_lookup');

		//Check if the session exists on every page load
		if(!isset($_SESSION['splash_me_conf'])){

			$_SESSION['splash_me_conf'] = array();
			
		}


		if(!isset($_SESSION['splash_me_conf']['time_set'])){
			
			//Set the time
			$_SESSION['splash_me_conf']['time_set'] = date("U", time());

			//if 'show' var not set then set it
			if(!isset($_SESSION['splash_me_conf']['show'])) {

				$_SESSION['splash_me_conf']['show'] = 'TRUE';

			}

		}				

		//If 'show' var is TRUE perform redirect
		if($_SESSION['splash_me_conf']['show'] === 'TRUE') {		

			//If user is not logged in
			if(!$GLOBALS['user']->uid){
					
				global $base_url;

				//If view equals 'full page'
				if (variable_get('splash_me_view_type') == 0) {
					
					if (arg(1) !== $splashPage){

						//Redirect to the splash screen
						drupal_goto($base_url . '/node/' . $splashPage);	

					}

				} else {

					//Assign some values to the Drupal.settings object
					drupal_add_js(
						array(
						  'splashMe' => array(
						    'jQuerySelector' => variable_get('splash_me_modal_content'),
						    'modalWidth' => variable_get('splash_me_modal_width'),
						    'overlayOpacity' =>variable_get('splash_me_modal_opacity'),
						    'overlayColour' =>variable_get('splash_me_overlay_colour'),
						    'modalClose' => variable_get('splash_me_modal_close'),
						    'ajaxUrl' => $base_url . '/node/' . variable_get('splash_me_node_lookup'),
						    'delayTime' => variable_get('splash_me_modal_delay'),
						    'continueLinkClose' => variable_get('splash_me_continue_close_link')
						  ),
						),
						'setting'
					);			

					//Place the JS file on the page
					drupal_add_js($base_url . '/sites/all/modules/splash_me/includes/js/splash-me.js', array(
					    'weight' => '-1000',
					    'type' => 'external',
					  )
					);

				}

			}

		}
		
		//Check if Developer mode is set
		$moduleMode = variable_get('splash_me_dev_mode');
		$sesClearTime = ($moduleMode == 1) ? 10 : 60 * 60 * 24;

		//Test to see if expiery time is up
		if (date("U", time())  >= $_SESSION['splash_me_conf']['time_set'] + ($sesClearTime)){

			//If the time is up unset the var and reset the process
			unset($_SESSION['splash_me_conf']);

		} else {

			//Prevent further redirects for user
			$_SESSION['splash_me_conf']['show'] = 'FALSE';

		}
	
	}

	//Callback for 'splash-me-node-results' url
	function splash_me_get_nodes($string) {

		//Set up DB query and assign to a variable
		$result = db_query("SELECT title, nid FROM {node} WHERE title LIKE '%$string%' LIMIT 10");
		
		//Assign array to var
		$matches = array();
		
		//Loop through the query results
		foreach($result as $item) {

			//Add data from the DB query result to the array
			$matches[$item->title] = check_plain($item->title);
			$matches[$item->nid] = check_plain($item->nid);

		}



		//Output the array as JSON data
		drupal_json_output($matches);

		exit;

	} 

	function splash_me_custom_theme() {

		if (arg(0) == 'node' && arg(1) == variable_get('splash_me_node_lookup')) {
			
			return variable_get('splash_me_themes');

		}

	}

	//Add a class to the body tag on the splash page
	function splash_me_preprocess_html(&$vars) {

		if (arg(0) == 'node' && arg(1) == variable_get('splash_me_node_lookup')) {

			$vars['classes_array']['class'] = 'splash_me_page';

		}

	}

	function splash_me_node_view($node) {

		if (variable_get('splash_me_continue_link')) {


			$continueText = variable_get('splash_me_continue_link_text');
			$continueClose = variable_get('splash_me_continue_close_link');
			$continueUrl = ($continueClose == 1) ? '#' : variable_get('splash_me_continue_url');
			$continueId = ($continueClose == 1) ? 'id="splash-me-close"' : '';

			$node->content['splash_me_continue_link'] = array(
				"#markup"=> '<a href="'. $continueUrl .'" '. $continueId .' class="splash-me-continue" title="Continue to the site">'. $continueText .'</a>',
				"#weight"=> 100
			);              

		}
		
		return $node;
	}

