<?php 

	/**
	 *@file
	 *splash_me.module
	 */

	//Create the menu item for the admin panel
	function splash_me_menu() {
  	
	  	$items = array();

		$items['admin/config/user-interface/splash_me'] = array(
			'title' => 'Splash Me',
			'description' => 'Configuration for the Splash Me module.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('splash_me_admin'),
			'access arguments' => array('administer users'),
			'file' => '/includes/splash_me.admin.inc',
			'type' => MENU_NORMAL_ITEM,
		);

		//Setup callback function for the above menu
		$items['splash-me-node-results'] = array(
			'page callback' => 'splash_me_get_nodes',
			'access arguments' => array('view published content'),
			'type' => MENU_CALLBACK,
		);

		return $items;

	}


	//Get the values from admin page
	$splashPage = variable_get('splash_me_node_lookup');
	//Get current url path
	$currentPage = current_path();



	//Check if the session exists on every page load
	function splash_me_init() {	

		if(!isset($_SESSION['splash_me_conf'])){

			$_SESSION['splash_me_conf'] = array();
			
		}	

	}


	//if 'show' var not set then set it
	if(!isset($_SESSION['splash_me_conf']['show'])) {

		$_SESSION['splash_me_conf']['show'] = 'TRUE';

	}


	//If 'show' var is TRUE perform redirect
	if($_SESSION['splash_me_conf']['show'] === 'TRUE') {		

		//If user is not logged in
		if(!$GLOBALS['user']->uid){
			
			if ($currentPage !== ('node/' . $splashPage)){
				//Redirect to the splash screen
				drupal_goto('node/' . $splashPage);			
			}

		}

	}

	//Prevent further redirects for user
	$_SESSION['splash_me_conf']['show'] = 'FALSE';




	//Callback for 'splash-me-node-results' url
	function splash_me_get_nodes($string) {

		//Set up DB query and assign to a variable
		$result = db_query("SELECT title, nid FROM {node} WHERE title LIKE '%$string%' LIMIT 10");
		
		//Assign array to var
		$matches = array();
		
		//Loop through the query results
		foreach($result as $item) {

			//Add data from the DB query result to the array
			$matches[$item->title] = check_plain($item->title);
			$matches[$item->nid] = check_plain($item->nid);

		}

		//Output the array as JSON data
		drupal_json_output($matches);

		exit;

	} 

	function splash_me_custom_theme() {

		if (arg(0) == 'node' && arg(1) == variable_get('splash_me_node_lookup')) {

			return variable_get('splash_me_themes');

		}

	}

